# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - terraform/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
# - task: TerraformInstaller@0
#   inputs:
#     terraformVersion: 'latest'
#   displayName: 'Install Terraform'
# - task: TerraformCLI@0
#   inputs:
#     command: 'init'
#     workingDirectory: 'terraform'
#   displayName: 'terraform init'
# - task: TerraformCLI@0
#   inputs:
#     command: 'plan'
#     workingDirectory: 'terraform'
#   displayName: 'terraform plan'
- script: pip install bridgecrew
  displayName: 'Install the Bridgecrew CLI'
- script: bridgecrew -d terraform
  displayName: 'Scan with Bridgecrew'
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

